In [1]:
import pandas as pd
#Importar biblioteca/Pandas
#tabela1 = tabela1.iloc[:]  CORTAR

tabela1 = pd.read_excel("1A.XLSX", skiprows=[4])
tabela2 = pd.read_excel("1B.XLSX", skiprows=[4])
tabela3 = pd.read_excel("1C.XLSX", skiprows=[4])
tabela4 = pd.read_excel("1D.XLSX", skiprows=[4])
tabela5 = pd.read_excel("2A.XLSX", skiprows=[4])
tabela6 = pd.read_excel("2B.XLSX", skiprows=[4])
tabela7 = pd.read_excel("2C.XLSX", skiprows=[4])
tabela8 = pd.read_excel("2D.XLSX", skiprows=[4])
tabela9 = pd.read_excel("2E.XLSX", skiprows=[4])
tabela10 = pd.read_excel("3A.XLSX", skiprows=[4])
tabela11 = pd.read_excel("3B.XLSX", skiprows=[4])
tabela12 = pd.read_excel("3C.XLSX", skiprows=[4])
tabela13 = pd.read_excel("4A.XLSX", skiprows=[4])
tabela14 = pd.read_excel("4B.XLSX", skiprows=[4])



#Ler tabelas do excel

tabela = pd.concat([tabela1, tabela2,tabela3,tabela4,tabela5, tabela6, tabela7, tabela8, tabela9, tabela10, tabela11, tabela12, tabela13, tabela14])
#Concatenar tabelas

display(tabela)
#Visualizar Tabela concatenada

tabela.to_excel("Lista Piloto 1 anos.xlsx", index=False)
#Importa nova planilha para excel

,Unidade,093106 - EMEF - DILERMANDO DIAS DOS SANTOS,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Turma,2360398 - 1A,Situação,Organizada,Ano Letivo,2022,Turno/Duração,Tarde 05:00h,NaT,NaN,NaN,NaN,NaN,NaN
1,Descrição,ENS REG / ENS FUND9A / CICLO I / 1º ANO / ANUA...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,7008602,000121446095-1/SP,183429129140,1,ALEJANDRO WALLACE ANDRADE ARAUJO,LUANA DE ANDRADE,2015-07-24 00:00:00,2018-01-24 00:00:00,2021-12-08,NaN,ATIVO,INICIAL,1º Ano,NaN
4,7658264,000122490181-2/SP,183278384902,2,ANA JULIA DE ASSIS MELO,MICHERLANY MOREIRA DE ASSIS,2015-09-13 00:00:00,2020-12-03 00:00:00,2021-12-08,NaN,ATIVO,INICIAL,1º Ano,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37,6308798,000114666548-9/SP,128231035116,NaN,MARIA VITORIA BERALDO DE LIMA SILVA,LETICIA BERALDO,2012-04-17 00:00:00,2015-02-19 00:00:00,2021-12-20,NaN,VÍNCULO INDEVIDO,INICIAL,4º ANO,NaN
38,7531397,000121871938-2/SP,127366713766,NaN,MECIAS OLIVEIRA DE SOUZA JUNIOR,BIANCA OLIVEIRA FRANCA,2010-12-03 00:00:00,2020-01-15 00:00:00,2021-12-20,NaN,VÍNCULO INDEVIDO,INICIAL,4º ANO,NaN
39,7377469,000121509856-X/SP,124252464527,NaN,NICOLAS BERALDO DE LIMA,MARIA LUIZA BERALDO,2012-07-15 00:00:00,2019-06-25 00:00:00,2022-03-08,NaN,TRANSFERIDO,INICIAL,4º ANO,NaN
40,6309461,000115458137-8/SP,128203010880,NaN,RANIELE ALVES DOS SANTOS,MARIA ROSINEIDE DOS SANTOS,2013-01-31 00:00:00,2015-02-20 00:00:00,2021-11-19,NaN,VÍNCULO INDEVIDO,INICIAL,4º ANO,NaN
41,5624955,000114546323-X/SP,128069565879,NaN,RENAN GABRIEL OLIVEIRA DE LIMA,MARIA JOSILENE OLIVEIRA DE LIMA,2011-09-27 00:00:00,2011-12-01 00:00:00,2022-01-06,NaN,VÍNCULO INDEVIDO,INICIAL,4º ANO,NaN